export const SIGN_IN = "/screen/authen/signin"
export const SIGN_UP = "/screen/authen/SignUp"
export const FORGOT_PASSWORD = "/screen/authen/ForgotPassword"
export const AVAILABILITY = "/screen/availability/Availability"
export const BANK = "/screen/bank/Bank"
export const BOOKINGS = "/screen/bookings/Bookings"
export const CHANGE_PASSWORD = "/screen/profile/ChangePassword"
export const EDIT_PROFILE = "/screen/profile/EditProfile"
export const MANAGER_PHOTOS = "/screen/profile/ManagePhotos"
export const PROFILE_MENU = "/screen/profile/ProfileMenu"
export const SUPPORT = "/screen/profile/Support"
export const SERVICE_DETAIL = "/screen/services/ServiceDetail"
export const SERVICES = "/screen/services/Services"
export default {};
