const ROUTER = {
  HOME: 'Home',
  PROFILE: 'Profile',
  MESSAGES: 'Messages',
  BOOKINGS: 'Bookings',
  AVAILABILITY: 'Availability',
  BANK: 'Bank account',
  BOOKING_DEAIL: 'Booking Detail',
  ATHLETE_DETAIL: "Athlete Detail",
  SERVICES: 'Services',
  SIGN_IN: 'Signin',
  SIGN_UP: 'Signup',
  FORGOT_PASSWORD: "Forgot Password?",
  EMAIL_VERTIFICATION: "Email Verification",
  RESET_PASSWORD: "Create New Password",
  CHANGE_PASSWORD: 'Change Password',
  EDIT_PROFILE: 'Edit Profile',
  EDIT_GALLERY: 'Edit Gallery',
  SERVICE_DETAIL: 'Service Detail',
  PHOTOS: 'Manage Photos',
  MY_CARD: 'My Card',
  SUPPORT: 'Request Support',
};
export default ROUTER;
